server:
  port: 8080
 
spring:
    profiles: 
        active: prod
     
--- 
 
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        password: sts@9890
        url: jdbc:postgresql://localhost:5432/employee
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true  


---
spring:
    config:
        activate:
            on-profile: qa
    datasource:
        password: sts@9890
        url: jdbc:postgresql://localhost:5432/employee-qa
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true 
        
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        password: sts@9890
        url: jdbc:postgresql://localhost:5432/employee-prod
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true   
        
management:
    endpoints:
        web:
            exposure:
                include: "*"    
                exclude: "env,beans"